### ISSUE TITLE
[Fleet] After enrolling a windows agent with endpoint, it appears twice on Security/Hosts

### ISSUE THREAD

**Issue by skh** [elastic/endpoint#19]
After installing/enrolling elastic-agent with a policy containing endpoint, I see the windows host twice in Security/Hosts:

![image](https://user-images.githubusercontent.com/189073/110133535-b47fb200-7dcc-11eb-9689-beacbfd072d5.png)

When I first looked at this screen the "Last seen" times were only seconds apart.

I see it only once in Security/Administration:

![image](https://user-images.githubusercontent.com/189073/110133662-db3de880-7dcc-11eb-90f9-002e3d23a3cf.png)

and also only once in Fleet/Agents:

![image](https://user-images.githubusercontent.com/189073/110133754-f6105d00-7dcc-11eb-9432-e2b4dd7310cf.png)

Version: 7.11.2

Exact steps:

* Install 7.11.2 on cloud, navigate to fleet, add elastic-agent to default policy
* Add agent, copy command to enroll on windows

* On a fresh VirtualBox Windows 10 64bit home, paste command into PowerShell without admin privileges
* get error, repeat in a PowerShell with admin privileges

* go back to Fleet UI, see one (healthy) agent
* navigate to Security/Hosts, see two hosts

**Comment by ferullo** [comment]
@dikshachauhan-qasource can you private message me credentials to see this bug in the system you reproduced it in. I can't reproduce it.

**Comment by ferullo** [comment]
It's been pointed out to me this issue is a year old. I'm going to close this issue since I couldn't repro it. It someone else can feel free to reopen it.

**Comment by dikshachauhan-qasource** [comment]
Hi @ferullo 

Currently we have observed that this issue is **occuring on 8.0.1 and 8.1.2 released builds as well using AWS windows server machines.**

**NOTE:** We could not try it using vSphere machines as today vSphere was too slow and machines weren't accessible. We will share the 8.2.0 observations as well with you by tomorrow.

For now, we have attached 8.1.2 screenshots for your reference:
![image](https://user-images.githubusercontent.com/72375798/161988683-dc0e36fa-b46e-4ff1-9c4b-e904253b0ee2.png)

![image](https://user-images.githubusercontent.com/72375798/161988457-163d9788-4292-443d-b52b-81f8782b5e8e.png)

Hence, we are reopening this ticket.

Please let me know if you need more info.

Thanks
QAS

**Comment by ferullo** [comment]
I looked at that server. I'm not sure why, but the server is changing its name. from WIN-... to EC2AMAZ-... while Agent is installed. That's why two entries are appearing in the Hosts page. The WIN-... host name appeared in early documents then transitions to EC2AMAZ-...

Can you verify you see the same thing then close this? I confirmed its the same host that changes its domain name by verifying that the `host.os.mac` value stays the same. One other way to confirm what I'm saying is the case is to just wait for longer before installing Agent on the host so the host name changes to EC2AMAZ-... before Agent is installed.

**Comment by dikshachauhan-qasource** [comment]
Hi @ferullo 

We attempted same on 8.2 BC2 build as well and observed same issue for AWS machines. While vSphere machine had only one entry under Hosts tab.

As mentioned we waited for more than half an hour after creating AWS Windows VM before installing the agent. And Almost half day was passed and still it was showing 03 entries this time under host tab. 

**I'll keep an eye for some more time till the other entries get obsolete as it happened on 8.1.2 environment. After this i'll close this issue.**

Screenshots for 8.2 BC2 environment:
![image](https://user-images.githubusercontent.com/72375798/162187678-5ec945d1-f222-4ae8-bb6b-1165c2a261ea.png)

![image](https://user-images.githubusercontent.com/72375798/162187779-1a6494ec-5274-49c7-b2c0-36eaa2847a22.png)


Thanks
QAS
