### ISSUE TITLE
Elastic Endpoint Crashes Beyond Compare

### ISSUE THREAD

**Issue by scooterchris** [elastic/endpoint#48]
Elastic Endpoint Security on Windows causes Beyond Compare to crash on startup.

Windows 10 Pro.
Elastic Endpoint Security installed (current version).
Install Beyond Compare 4.4.6 trial version from: https://www.scootersoftware.com/download.php
Use default installation options in install wizard.
After install, double click on Beyond Compare shortcut on desktop.
Beyond Compare crashes.

Beyond Compare shows error message:
Assertion failure (C:\ContinuaCI_AgentWorkspace\Ws\11930\Source\BeyondCompare\Source\Vfs\VfsManagerImpl.pas, line 748).

Beyond Compare 4.4.6 runs without issue in the same Windows 10 Pro environment when Elastic Endpoint Security is not installed.

**Comment by nfritts** [comment]
Hi Chris,

Hopefully this can help you and your customers.

For multiple of the features Endpoint provides, it momentarily suspends threads at times.  I can't tell if there is an easy exception to catch in Delphi or not, but effectively when Beyond Compare is calling Resume on one of its threads, we have it suspended as well.  I think from looking at the docs briefly this might happen automatically if you create a non-suspended thread (For a non-suspended thread, TThread seems to start it suspended and then call resume as part of the initialization).  Or it could be happening when Start is called on a thread that was intentionally created suspended.  

I'm not very familiar with Delphi and I don't know the right way to handle the exceptions that are raised when the attempt to resume the thread results in a thread that is still suspended.  Ideally the exception wouldn't cause the program to crash.

I don't think any of this has changed since you originally reported issues back in January, parts of our code that Suspend threads can run asynchronously and so my guess is the problem never went away, but the race was less likely to happen on one of the versions.  

There are two ways that you can work around this:
disable Memory Threat in the policy (this feature seems to most reliably cause the issue):
![image](https://user-images.githubusercontent.com/56593026/236925645-76694268-0fd8-4667-ac31-d7736e0e481e.png)


or add a Trusted Applicaiton entry:
![image](https://user-images.githubusercontent.com/56593026/236925676-ef47832c-36a3-4118-b8a9-7adba5b8288d.png)
