### ISSUE TITLE
[Enhancement Request] Exceptions to Application Blocklist

### ISSUE THREAD

**Issue by MakoWish** [elastic/endpoint#68]
We would like to start leveraging the Application Blocklist some more, but I fear managing it will become too clunky to be as effective as we would like. There are applications we would like to block, but just about every application we want to block does have exceptions documented and approved by our leadership. 

Just to give one example, we only allow [cough... gag...] Microsoft Edge as our standard browser and would like to block all others. That sounds simple enough, but we do have exceptions for our Application Development team who needs to test web apps with Firefox and Chrome for compatibility. At this point, it seems creating a separate Elastic Agent policy is the only workaround to allow them to bypass the Blocklist, but as mentioned, this is only one example. The number of Elastic Agent policies would grow out of hand for all the exceptions to Blocklists.

I would like to propose exceptions to the Blocklist that can be managed just like Security Detection Rule Exceptions and Endpoint Exceptions (`host.name`, `user.name`, expiration date of the exception, etc.). This would allow us to maintain specific exceptions to the Blocklists and not have to create separate Elastic Agent policies every time we need to make an exception to Blocklists.

**Comment by ferullo** [comment]
Hi @MakoWish I'm not sure how giving blocklisting its own exception list would solve your problem since you'd still have to attach those blocklist exceptions to Endpoint policies the same way as the existing Endpoint exception list. (Maybe what you really want is a way to attach multiple Endpoint exception lists to a single policy?) Regardless, I think there are currently two possible solutions for you.

If you have a platinum or enterprise subscription you can create per-policy Endpoint alert exception lists (as well as still have global ones) and then attach each per-policy exception list to different Agent/Endpoint policies for each user group. That is, as far as I can understand, effectively what you are asking for. If you have a platinum or enterprise subscription and that doesn't give you what you need can you explain more why it doesn't work?

At all subscription levels another solution is to include `user.name` or `host.name` as one of the fields in the blocklist exceptions you are creating. While those exceptions will be sent to all Endpoints attached to the policy/exception list, they will only prevent blocklisting for the users/systems where those fields match. That will let you globally manage these exceptions but have them function on a per-user/host basis.

The only part of your request that I think has no current solution is alert exception expiration dates. While rule exceptions can have expiration dates, Endpoint exceptions cannot.

**Comment by MakoWish** [comment]
Hi @ferullo, 

Yeah, I think you are misunderstanding. Exceptions to Blocklists really is the only solution here. 

A Blocklist can be assigned to one or more Elastic Agent policies (or Global), and while we do have a total of 28 policies right now, there are only three main policies for Windows client computers: Test, Control, and Production. Let's say we want to test blocking Firefox with the Blocklist. I would first create the Blocklist and apply it to our Test policy. If everything seems good, we then also apply it to the Control policy. After that bakes in for a while without issue, we would then also apply it to our Production policy. However, as mentioned before, I would need to create some exceptions to that Blocklist to allow Firefox on our Application Development team's computers. Unfortunately, Blocklists do not allow adding anything like `is not one of: Computer1, Computer2`. You are only given three options in a Blocklist: Hash, Path, or Signature. There is no option to specify users, computers, etc., and there is definitely no option for specifying an Expiration. 

I understand you can create multiple policies to apply those Blocklists to, but as mentioned in the original post, there are dozens of exceptions that would be applied to different groups of computers or teams of users. This would create an unmanageable sprawl of Elastic Agent policies, so that is not really a solution. The only way to resolve this is with Exceptions for Blocklists.

**Comment by MakoWish** [comment]
Any more input on this? We have leveraged our DLP solution to block software executions for some time now, but we are looking to change DLP vendors pretty soon here. I proposed using Elastic Agent (with Endpoint) to migrate that blocklist to, but without a way of creating exceptions for certain users or computers, Elastic will just not do the job. 

For just one example... We want to block all browsers except Edge (I know... gag... ), but we need to allow other browsers for just our AppDev team to test. There needs to be a way to create an exception like:

```
OS IS Windows
    AND file.Ext.code_signature IS ONE OF 
        Mozilla Corporation
    AND host.name IS NOT ONE OF
        Computer01,Computer02,Computer03
```

Excluding devices by `host.name` or users by `user.name` needs to happen here.

**Comment by MakoWish** [comment]
It would also be nice to allow customizing the block notification, but that would be a "nice to have" where the ability to create exceptions is really a "must have". 

Instead of `Operation did not complete successfully, because the file contains a virus or potentially unwanted software`, it would be nice to customize that to say, `This software has been blocked due to policy. If you feel this to be in error, please contact the IT Help Desk.`

![block_notice](https://github.com/elastic/endpoint/assets/26614684/aa73743e-f88d-48de-a297-fc4b99a044ca)

**Comment by ferullo** [comment]
Sorry I didn't respond a month ago, I missed your original reply.

>> At all subscription levels another solution is to include user.name or host.name as one of the fields in the blocklist exceptions you are creating

> Not possible. You are only given three options in a Blocklist: Hash, Path, or Signature. There is no option to specify users, computers, etc., and there is definitely no option for specifying an Expiration.

I was confusing. For this I meant to add an Endpoint Alert Exception (Security App -> Rules -> Shared Exception Lists -> Endpoint Security Exception List) that only matches on Blocklist alerts. So if you have a Linux Blocklist entry for

```
OS IS Linux
file.path IS /home/vagrant/my-blocklist-exe
```

You could add a corresponding Endpoint Alert Exception like this so the file isn't blocked the listed hosts. The `message` field limits the exception to just Blocklist alerts, then you can add whatever other criteria you want to use to limit the hosts it is effective on. As I mentioned before, this exception would be delivered globally to all hosts but only work on the hosts that match its criteria.

```
OS IS Linux
file.path IS /home/vagrant/my-blocklist-exe
AND event.code IS malicious_file
AND message IS Blocklist Prevention Alert
AND host.hostname IS my-linux
```

I see how this isn't exactly what you're asking for since it requires entries in two places (the blocklist and the exception) but functionally I think it matches your requirement and works right now.

> It would also be nice to allow customizing the block notification ...

Unfortunately, the notification you screenshotted comes from Windows itself and we can't customize it or prevent it from displaying when we block a file. You can customize the Elastic notification that appears in the bottom right of the screen via the Endpoint policy, as you probably already know.

**Comment by MakoWish** [comment]
This is perfect! Not sure why the entire Endpoint Exception option didn't cross my mind. <FacePalm />

Yeah, it would be nice to have the exceptions on the Blocklist items themselves, but it seems this will work. I am going to test it out with my team now.

**Comment by MakoWish** [comment]
So, this **_mostly_** solves the issue. There is unfortunately no way to set an expiration date/time on Endpoint Exceptions. :-(

**Comment by ferullo** [comment]
Great, I'm glad that (mostly) works for you. 🚀 

You're right that there is no way to set an Endpoint Alert Exception expiration. I'll add that request to our backlog and close this issue if you don't mind 😄 .

**Comment by MakoWish** [comment]
If you would like to close this one, may I open a new ER for Endpoint Exception Expirations?

**Comment by ferullo** [comment]
Yes, please do. Can you open it in https://github.com/elastic/kibana and tag me on it.

**Comment by MakoWish** [comment]
https://github.com/elastic/kibana/issues/186552
