### ISSUE TITLE
Logstash output proxy is ignored

### ISSUE THREAD

**Issue by intxgo** [elastic/endpoint#77]
# Description

When Logstash is configured as output, with proxy, the proxy setting has no effect on Elastic Endpoint (Elastic Defend integration).

# Affected version

All current Endpoint versions with Logstash output support.

**Comment by DBchmnn** [comment]
Hi,

currently we cannot continue with rollout of Elastic Defend because of this bug. :(
It would be nice if this will be fixed as soon as possible.

Regards
Dominik

**Comment by DBchmnn** [comment]
Sounds great. But it is not listed as a bug fix in the release notes yet, right?
https://www.elastic.co/guide/en/security/current/release-notes-header-8.15.0.html#bug-fixes-8.15.1

We have to upgrade to version 8.15.1 first in order to check if the issue is resolved on our side. This will take some more weeks.

**Comment by intxgo** [comment]
Closing as we've added socks5 proxy support. Socks5 GSSAPI authentication is not implemented, but we can open another issue if there's a need for it.
